export const letters: string[] = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
];

const keysBySymbol = {
  leftLittleFinger: ["&", "a", "q", "w", "<", "ctrl", "maj", "fn"],
  leftRingFinger: ["z", "é", "s", "x"],
  leftMiddleFinger: ["e", "d", "c"],
  leftIndexFinger: ["(", "-", "r", "t", "f", "g", "c", "v"],
  leftThumb: [" ", "alt"],
  rightLittleFinger: [
    "Enter",
    "Backspace",
    "=",
    "$",
    "*",
    "^",
    "ù",
    "!",
    ")",
    "p",
    "m",
  ],
  rightRingFinger: ["à", "o", "l"],
  rightMiddleFinger: ["ç", "i", "k", ","],
  rightIndexFinger: ["è", "_", "u", "y", "h", "j", "b", "n"],
  rightThumb: [" "],
};

export const keysMap = new Map([
  [keysBySymbol.leftLittleFinger, "auriculaire gauche"],
  [keysBySymbol.leftRingFinger, "annulaire gauche"],
  [keysBySymbol.leftMiddleFinger, "majeur gauche"],
  [keysBySymbol.leftIndexFinger, "index gauche"],
  [keysBySymbol.leftThumb, "pouce gauche"],
  [keysBySymbol.rightLittleFinger, "auriculaire droit"],
  [keysBySymbol.rightMiddleFinger, "annulaire droit"],
  [keysBySymbol.rightMiddleFinger, "majeur droit"],
  [keysBySymbol.rightIndexFinger, "index droit"],
  [keysBySymbol.rightThumb, "pouce droit"],
]);
